export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

export const DELETE_MAIN_CATEGORIES = 'DELETE_MAIN_CATEGORIES';
export const DELETE_MAIN_CATEGORIES_SUCCESS = 'DELETE_MAIN_CATEGORIES_SUCCESS';

export const DELETE_SUB_CATEGORIES = 'DELETE_SUB_CATEGORIES';
export const DELETE_SUB_CATEGORIES_SUCCESS = 'DELETE_SUB_CATEGORIES_SUCCESS';
export const DELETE_SUB_CATEGORIES_FAILURE = 'DELETE_SUB_CATEGORIES_FAILURE';

export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
export const FETCH_ALL_CATEGORIES_SUCCESS = 'FETCH_ALL_CATEGORIES_SUCCESS';
export const FETCH_ALL_CATEGORIES_FAILURE = 'FETCH_ALL_CATEGORIES_FAILURE';

export const ADD_MAIN_CATEGORY = 'ADD_MAIN_CATEGORY';
export const ADD_MAIN_CATEGORY_SUCCESS = 'ADD_MAIN_CATEGORY_SUCCESS';

export const EDIT_SUB_CATEGORIS_TO_MAIN = 'EDIT_SUB_CATEGORIS_TO_MAIN';
export const EDIT_SUB_CATEGORIS_TO_MAIN_SUCCESS = 'EDIT_SUB_CATEGORIS_TO_MAIN_SUCCESS';
// TODO just one error action type