export const FETCH_PRODUCT_INFO = 'FETCH_PRODUCT_INFO';
export const FETCH_PRODUCT_INFO_SUCCESS = 'FETCH_PRODUCT_INFO_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

export const DELETE_MAIN_CATEGORIES_FROM_PRODUCT = 'DELETE_CATEGORIES_FROM_PRODUCT';
export const DELETE_MAIN_CATEGORIES_FROM_PRODUCT_SUCCESS = 'DELETE_MAIN_CATEGORIES_SUCCESS';

export const DELETE_SUB_CATEGORIES_FROM_PRODUCT = 'DELETE_SUB_CATEGORIES';
export const DELETE_SUB_CATEGORIES_FROM_PRODUCT_SUCCESS = 'DELETE_SUB_CATEGORIES_SUCCESS';

export const FETCH_PRODUCT_CATEGORIES = 'FETCH_PRODUCT_CATEGORIES';
export const FETCH_PRODUCT_CATEGORIES_SUCCESS = 'FETCH_PRODUCT_CATEGORIES_SUCCESS';
