export const FETCH_PRODUCT_INFO = 'FETCH_PRODUCT_INFO';
export const FETCH_PRODUCT_INFO_SUCCESS = 'FETCH_PRODUCT_INFO_SUCCESS';

export const FETCH_FAILURE = 'FETCH_FAILURE';

export const UPDATE_PRODUCT_INFO = 'UPDATE_PRODUCT_INFO';
export const UPDATE_PRODUCT_INFO_SUCCESS = 'UPDATE_PRODUCT_INFO_SUCCESS';
export const UPDATE_PRODUCT_INFO_FAILURE = 'UPDATE_PRODUCT_INFO_FAILURE';

export const DELETE_MAIN_CATEGORIES_FROM_PRODUCT = 'DELETE_CATEGORIES_FROM_PRODUCT';
export const DELETE_MAIN_CATEGORIES_FROM_PRODUCT_SUCCESS = 'DELETE_MAIN_CATEGORIES_SUCCESS';

export const DELETE_SUB_CATEGORIES_FROM_PRODUCT = 'DELETE_SUB_CATEGORIES';
export const DELETE_SUB_CATEGORIES_FROM_PRODUCT_SUCCESS = 'DELETE_SUB_CATEGORIES_SUCCESS';

export const FETCH_PRODUCT_CATEGORIES = 'FETCH_PRODUCT_CATEGORIES';
export const FETCH_PRODUCT_CATEGORIES_SUCCESS = 'FETCH_PRODUCT_CATEGORIES_SUCCESS';

export const ADD_SUB_CATEGORIES_TO_PRODUCT = 'ADD_SUB_CATEGORIES_TO_PRODUCT';
export const ADD_SUB_CATEGORIES_TO_PRODUCT_SUCCESS = 'ADD_SUB_CATEGORIES_TO_PRODUCT_SUCCESS';

export const ADD_MAIN_CATEGORIES_TO_PRODUCT = 'ADD_MAIN_CATEGORIES_TO_PRODUCT';
export const ADD_MAIN_CATEGORIES_TO_PRODUCT_SUCCESS = 'ADD_MAIN_CATEGORIES_TO_PRODUCT_SUCCESS';

export const CLEAR_PRODUCT_INFO = 'CLEAR_PRODUCT_INFO';
export const STORE_PRODUCT_MAIN_CATEGORIES = 'STORE_PRODUCT_MAIN_CATEGORIES';
export const STORE_PRODUCT_SUB_CATEGORIES = 'STORE_PRODUCT_SUB_CATEGORIES';
export const STORE_PRODUCT_INFO = 'STORE_PRODUCT_INFO';

export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const ADD_NEW_PRODUCT_SUCCESS = 'ADD_NEW_PRODUCT_SUCCESS';
